#!/bin/bash
echo "[Step 1]. Prepare LVM"
ssh node1 "sudo ceph-volume lvm prepare --bluestore --data /dev/sda"
ssh node1 "sudo ceph-volume lvm prepare --bluestore --data /dev/sdb"
ssh node1 "sudo ceph-volume lvm prepare --bluestore --data /dev/sdc"
ssh node2 "sudo ceph-volume lvm prepare --bluestore --data /dev/sda"
ssh node2 "sudo ceph-volume lvm prepare --bluestore --data /dev/sdb"
ssh node2 "sudo ceph-volume lvm prepare --bluestore --data /dev/sdc"
ssh node3 "sudo ceph-volume lvm prepare --bluestore --data /dev/sda"
ssh node3 "sudo ceph-volume lvm prepare --bluestore --data /dev/sdb"
ssh node3 "sudo ceph-volume lvm prepare --bluestore --data /dev/sdc"
echo "[Step 2]. Start OSD"
ssh node1 "sudo systemctl restart ceph-osd\@0"
ssh node1 "sudo systemctl restart ceph-osd\@1"
ssh node1 "sudo systemctl restart ceph-osd\@2"
ssh node2 "sudo systemctl restart ceph-osd\@3"
ssh node2 "sudo systemctl restart ceph-osd\@4"
ssh node2 "sudo systemctl restart ceph-osd\@5"
ssh node3 "sudo systemctl restart ceph-osd\@6"
ssh node3 "sudo systemctl restart ceph-osd\@7"
ssh node3 "sudo systemctl restart ceph-osd\@8"
echo "[Step 3]. Reset device-class"
ssh node1 "ceph osd crush rm-device-class osd.0"
ssh node1 "ceph osd crush rm-device-class osd.1"
ssh node1 "ceph osd crush rm-device-class osd.2"
ssh node1 "ceph osd crush rm-device-class osd.3"
ssh node1 "ceph osd crush rm-device-class osd.4"
ssh node1 "ceph osd crush rm-device-class osd.5"
ssh node1 "ceph osd crush rm-device-class osd.6"
ssh node1 "ceph osd crush rm-device-class osd.7"
ssh node1 "ceph osd crush rm-device-class osd.8"
ssh node1 "ceph osd crush set-device-class ssd osd.0"
ssh node1 "ceph osd crush set-device-class ssd osd.1"
ssh node1 "ceph osd crush set-device-class ssd osd.2"
ssh node1 "ceph osd crush set-device-class ssd osd.3"
ssh node1 "ceph osd crush set-device-class ssd osd.4"
ssh node1 "ceph osd crush set-device-class ssd osd.5"
ssh node1 "ceph osd crush set-device-class ssd osd.6"
ssh node1 "ceph osd crush set-device-class ssd osd.7"
ssh node1 "ceph osd crush set-device-class ssd osd.8"
echo "[Ceph Cluster Preparaton Done]"
